# Generated by Django 4.1.7 on 2023-03-21 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_post_comments_post_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='engineer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts_engineer', to=settings.AUTH_USER_MODEL),
        ),
    ]
