# Generated by Django 4.1.7 on 2023-03-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_post_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='engineer',
        ),
    ]
