# Generated by Django 4.1.7 on 2023-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_business',
        ),
        migrations.AddField(
            model_name='post',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
